### ISSUE TITLE
failed to run demo data

### ISSUE THREAD

**Issue by shenwei356** [gcgreenberg/LexicHash#1]
Hi, I installed dependencies in a conda environment with `python==3.9`. And the demo command failed to run. Could you please help to check it?

```
(lexicHash) [shenwei@mBio LexicHash]$ python3 run_module.py --out ../LH_out --fasta data/NCTC1080/NCTC1080_reads.fasta.gz --n_hash 100 --max_k 32
===============================================================================
=================== SuffixHash Sequence Alignment Estimator ===================
===============================================================================
running lexichash on data/NCTC1080/NCTC1080_reads.fasta.gz
# hash functions: 100
minimum-maximum match length: 14-32

=================== SKETCHING READS ===================
# sequences: 1003
sketching took 0 minutes, 4 seconds

=================== PERFORMING PAIRWISE COMPARISON ===================
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/shenwei/app/miniconda3/envs/lexicHash/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/shenwei/app/miniconda3/envs/lexicHash/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/shenwei/Downloads/LexicHash/LexicHash/LexicHash.py", line 281, in get_matching_sets
    chars = (shared_sketches[seq_idxs, sketch_idx] >> 2*(MAX_K-k-1)) & 3
TypeError: unsupported operand type(s) for >>: 'float' and 'int'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shenwei/Downloads/LexicHash/run_module.py", line 55, in <module>
    main()
  File "/home/shenwei/Downloads/LexicHash/run_module.py", line 50, in main
    LexicHash.find_overlaps(**args)
  File "/home/shenwei/Downloads/LexicHash/LexicHash/LexicHash.py", line 50, in find_overlaps
    pair_match_lens = pairwise_comparison(sketches, n_seq, **args)
  File "/home/shenwei/Downloads/LexicHash/LexicHash/LexicHash.py", line 227, in pairwise_comparison
    all_matching_sets = prefix_tree_multiproc(sketches, n_hash, n_cpu, max_k, min_k)
  File "/home/shenwei/Downloads/LexicHash/LexicHash/LexicHash.py", line 246, in prefix_tree_multiproc
    all_matching_sets = pool.map(get_matching_sets, args, chunksize)
  File "/home/shenwei/app/miniconda3/envs/lexicHash/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/shenwei/app/miniconda3/envs/lexicHash/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: unsupported operand type(s) for >>: 'float' and 'int'
```

It seems that the `dtype` of `shared_sketches[seq_idxs, sketch_idx]` (`numpy.ndarray`) is `float`?

**Comment by gcgreenberg** [comment]
Hi @shenwei356, thanks for your post. I mistakenly made the sketches an "object" array. I have updated it to be np.uint64. This limits kmax to be <=32, but the demo should work now. I will work on a fix that allows for any kmax. 
Could you please pull the new file and try again? Thanks!

**Comment by shenwei356** [comment]
It works. Thanks for the prompt fix!

**Comment by shenwei356** [comment]
In the output, the third column (the longest command substring), is not very useful to tell the similarity between two sequences. According to the paper, you also use it as the similarity score. I'm thinking that you might sum up y(s1, s2) values higher than a threshold. 


````
# sorted output
1	14	14	+
1	16	25	-
1	23	17	+
1	49	14	-
1	116	14	-
1	157	16	+
1	185	15	-
1	213	15	+
1	229	14	+
1	271	14	+
1	302	16	+
1	307	16	+
1	313	32	+
1	328	32	+
1	334	27	+
1	345	15	-
1	361	30	-
1	361	29	+
1	368	21	+
1	371	23	+
1	372	14	+
1	397	14	-
1	472	32	-
1	496	28	+
1	509	28	+
1	514	22	+
1	516	22	+
1	600	26	-
1	607	32	-
1	632	32	+
1	635	26	-
1	646	14	-
1	690	15	-
1	739	28	-
1	807	14	+
1	864	14	-
1	886	14	+
2	152	25	+

```

**Comment by gcgreenberg** [comment]
Yes, I agree the "LexicHash score" is mostly useful in a relative way. We have also experimented with using sum(y(s1,s2)) above an initial threshold as the similarity measure. While we see fewer false positives this way at lower recalls, we did not see a performance improvement at practical recall values or for AUCs for ROC and precision-recall curves. 
Another reason we did not use sum(y(s1,s2)) is that the compute time increases quickly with lower initial thresholds.

**Comment by shenwei356** [comment]
Thanks for the valuable information.

> We have also experimented with using sum(y(s1,s2)) above an initial threshold as the similarity measure. While we see fewer false positives this way at lower recalls, we did not see a performance improvement at practical recall values or for AUCs for ROC and precision-recall curves.

Oh, it's kind of counterintuitive. Bringing false positives is not surprising as only the sum of lengths of shared subsequences is considered, while the relative locations are not checked. But how would it bring lower recalls. :smiling_face_with_tear: 

> Another reason we did not use sum(y(s1,s2)) is that the compute time increases quickly with lower initial thresholds.

I'm not sure if I understand it correctly. Summing should not bring too much computation burden.

**Comment by gcgreenberg** [comment]
I think the thing to note is that there are two thresholds here. One is the initial threshold T on the match length for summing over y(s1,s2) to get the similarity score. The second is the inference threshold S on the similarity score (i.e., sum(y(s1,s2)>T) when we want to filter pairs of reads.

When S is large, then the recall is likely low, because only pairs of reads with a large similarity score pass. For those pairs, when only max(y) is used, some false positives are expected due to short genomic repeats that minimap, e.g., would not consider a "real" match. 

However, this is mainly an issue for large S. Using sum(y>T) for smaller S we saw had a similar performance as max(y).

The reason sum(y>T) needs more computation is that we need to find all pairs of reads whose match length is greater than T for all masks, whereas max(y) only needs to find the largest one. We use a prefix tree structure, and obtaining max(y) is very quick, especially when you are only looking for a relatively small number of pairs of reads to output. We discuss this in our paper that will be published in Bioinformatics within a week or so :)

**Comment by shenwei356** [comment]
That makes sense.  Thanks for your explanation. 

Actually, the paper is already online for a few days.

**Comment by gcgreenberg** [comment]
Ok great!
